name: FortranPEG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.Deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Deployment
        id: Deployment
        uses: actions/deploy-pages@v4