name: FortranPEG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment
        uses: actions/deploy-pages@v4
        with:
          publish_dir: src/FrontEnd